import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Language = "uk" | "en";

export const translations = {
  uk: {
    appName: "Хвостик",
    pets: "Тварини",
    reminders: "Нагадування",
    settings: "Налаштування",
    addPet: "Додати тварину",
    noPets: "Немає тварин",
    noPetsSubtitle: "Натисніть + щоб додати свого улюбленця",
    noReminders: "Немає нагадувань",
    noRemindersSubtitle: "Додайте вакцинації щоб отримувати нагадування",
    remindersTotal: (n: number) => `${n} вакцинацій заплановано`,
    onePet: "1 тварина",
    manyPets: (n: number) => `${n} тварин`,
    addPetTitle: "Додати тварину",
    petType: "Вид тварини",
    basicInfo: "Основна інформація",
    name: "Ім'я",
    namePlaceholder: "Ім'я вашої тварини",
    breed: "Порода",
    breedPlaceholder: "Оберіть або введіть породу",
    birthdate: "Дата народження",
    birthdatePlaceholder: "РР-ММ-РРРР",
    weight: "Вага (кг)",
    color: "Забарвлення",
    colorPlaceholder: "Колір забарвлення",
    gender: "Стать",
    male: "Хлопчик",
    female: "Дівчинка",
    save: "Зберегти тварину",
    saving: "Збереження...",
    cancel: "Скасувати",
    back: "Назад",
    delete: "Видалити",
    errorName: "Вкажіть ім'я тварини",
    errorBirthdate: "Вкажіть дату народження",
    errorBirthdateFormat: "Невірний формат дати. Використовуйте ДД-ММ-РРРР",
    photoTitle: "Фото тварини",
    photoCamera: "Камера",
    photoGallery: "Галерея",
    cameraDenied: "Потрібен дозвіл на використання камери",
    permissionTitle: "Дозвіл",
    age: "Вік",
    lessThanMonth: "< 1 міс.",
    months: (n: number) => `${n} міс.`,
    oneYear: "1 рік",
    years2to4: (n: number) => `${n} роки`,
    yearsMany: (n: number) => `${n} років`,
    vaccinations: "Вакцинації",
    addVaccination: "Додати вакцинацію",
    noVaccinations: "Немає вакцинацій",
    documents: "Документи",
    addDocument: "Додати документ",
    noDocuments: "Немає документів",
    overdue: "Прострочено",
    soon7days: "Незабаром (7 днів)",
    thisMonth: "Цього місяця",
    planned: "Заплановано",
    next: "Наступна",
    done: "Зроблено",
    vet: "Ветеринар",
    notes: "Нотатки",
    profile: "Профіль тварини",
    details: "Деталі",
    seeAll: "Всі",
    newVaccine: "Нова вакцина",
    vaccineReminder: "Ви отримаєте нагадування за 7 днів до наступної вакцинації",
    quickPick: "Швидкий вибір",
    vaccinationInfo: "Інформація про вакцинацію",
    vaccineName: "Назва вакцини",
    vaccineDate: "Дата вакцинації",
    nextVaccineDate: "Наступна вакцинація",
    additionalInfo: "Додаткова інформація",
    saveVaccination: "Зберегти вакцинацію",
    deleteVaccination: "Видалити вакцинацію?",
    deleteVaccinationConfirm: "Вакцинацію буде видалено безповоротно.",
    deleteDoc: "Видалити документ?",
    deleteDocConfirm: "Документ буде видалено зі списку.",
    deletePet: "Видалити",
    deletePetConfirm: "Всі дані тварини будуть видалені безповоротно.",
    docTakePhoto: "Зробити фото",
    docGallery: "Вибрати з галереї",
    docFiles: "Вибрати з файлів",
    docCount: (n: number) => `${n} документів збережено`,
    language: "Мова",
    ukrainian: "Українська",
    english: "English",
    appearance: "Вигляд",
    about: "Про додаток",
    version: "Версія",
    notFound: "Тварину не знайдено",
    cat: "Кіт",
    dog: "Собака",
    rabbit: "Кролик",
    hamster: "Хом'як",
    guinea_pig: "Морська свинка",
    bird: "Птах",
    turtle: "Черепаха",
    reptile: "Рептилія",
    fish: "Риба",
    ferret: "Тхір",
    hedgehog: "Їжак",
    other: "Інше",
    selectBreed: "Оберіть породу",
    customBreed: "Інша порода",
    weightSelect: "Вага",
    today: "Сьогодні",
  },
  en: {
    appName: "Tailsy",
    pets: "Pets",
    reminders: "Reminders",
    settings: "Settings",
    addPet: "Add Pet",
    noPets: "No Pets Yet",
    noPetsSubtitle: "Tap + to add your first pet",
    noReminders: "No Reminders",
    noRemindersSubtitle: "Add vaccinations to get reminders",
    remindersTotal: (n: number) => `${n} vaccinations scheduled`,
    onePet: "1 pet",
    manyPets: (n: number) => `${n} pets`,
    addPetTitle: "Add Pet",
    petType: "Pet Type",
    basicInfo: "Basic Information",
    name: "Name",
    namePlaceholder: "Your pet's name",
    breed: "Breed",
    breedPlaceholder: "Select or enter breed",
    birthdate: "Date of Birth",
    birthdatePlaceholder: "DD-MM-YYYY",
    weight: "Weight (kg)",
    color: "Coat Color",
    colorPlaceholder: "Color / markings",
    gender: "Gender",
    male: "Male",
    female: "Female",
    save: "Save Pet",
    saving: "Saving...",
    cancel: "Cancel",
    back: "Back",
    delete: "Delete",
    errorName: "Please enter pet name",
    errorBirthdate: "Please enter date of birth",
    errorBirthdateFormat: "Invalid date format. Use DD-MM-YYYY",
    photoTitle: "Pet Photo",
    photoCamera: "Camera",
    photoGallery: "Gallery",
    cameraDenied: "Camera permission is required",
    permissionTitle: "Permission",
    age: "Age",
    lessThanMonth: "< 1 mo.",
    months: (n: number) => `${n} mo.`,
    oneYear: "1 year",
    years2to4: (n: number) => `${n} years`,
    yearsMany: (n: number) => `${n} years`,
    vaccinations: "Vaccinations",
    addVaccination: "Add Vaccination",
    noVaccinations: "No Vaccinations",
    documents: "Documents",
    addDocument: "Add Document",
    noDocuments: "No Documents",
    overdue: "Overdue",
    soon7days: "Due Soon (7 days)",
    thisMonth: "This Month",
    planned: "Planned",
    next: "Next",
    done: "Done",
    vet: "Veterinarian",
    notes: "Notes",
    profile: "Pet Profile",
    details: "Details",
    seeAll: "All",
    newVaccine: "New Vaccine",
    vaccineReminder: "You will get a reminder 7 days before the next vaccination",
    quickPick: "Quick Pick",
    vaccinationInfo: "Vaccination Info",
    vaccineName: "Vaccine Name",
    vaccineDate: "Vaccination Date",
    nextVaccineDate: "Next Vaccination",
    additionalInfo: "Additional Info",
    saveVaccination: "Save Vaccination",
    deleteVaccination: "Delete Vaccination?",
    deleteVaccinationConfirm: "This vaccination will be permanently deleted.",
    deleteDoc: "Delete Document?",
    deleteDocConfirm: "This document will be removed from the list.",
    deletePet: "Delete",
    deletePetConfirm: "All pet data will be permanently deleted.",
    docTakePhoto: "Take Photo",
    docGallery: "Choose from Gallery",
    docFiles: "Browse Files",
    docCount: (n: number) => `${n} documents stored`,
    language: "Language",
    ukrainian: "Українська",
    english: "English",
    appearance: "Appearance",
    about: "About",
    version: "Version",
    notFound: "Pet not found",
    cat: "Cat",
    dog: "Dog",
    rabbit: "Rabbit",
    hamster: "Hamster",
    guinea_pig: "Guinea Pig",
    bird: "Bird",
    turtle: "Turtle",
    reptile: "Reptile",
    fish: "Fish",
    ferret: "Ferret",
    hedgehog: "Hedgehog",
    other: "Other",
    selectBreed: "Select Breed",
    customBreed: "Other breed",
    weightSelect: "Weight",
    today: "Today",
  },
} as const;

export type Translations = typeof translations.uk;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const STORAGE_KEY = "@vethelper_language";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("uk");

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY).then((val) => {
      if (val === "uk" || val === "en") setLanguageState(val);
    });
  }, []);

  const setLanguage = useCallback(async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem(STORAGE_KEY, lang);
  }, []);

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t: translations[language] }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
