import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Language = "uk" | "en";

export const translations = {
  uk: {
    appName: "Хвостик",
    pets: "Тварини",
    reminders: "Нагадування",
    settings: "Налаштування",
    addPet: "Додати тварину",
    noPets: "Немає тварин",
    noPetsSubtitle: "Натисніть + щоб додати свого улюбленця",
    noReminders: "Немає нагадувань",
    noRemindersSubtitle: "Додайте вакцинації щоб отримувати нагадування",
    remindersTotal: (n: number) => `${n} вакцинацій заплановано`,
    onePet: "1 тварина",
    manyPets: (n: number) => `${n} тварин`,
    addPetTitle: "Додати тварину",
    petType: "Вид тварини",
    basicInfo: "Основна інформація",
    name: "Ім'я",
    namePlaceholder: "Ім'я вашої тварини",
    breed: "Порода",
    breedPlaceholder: "Оберіть або введіть породу",
    birthdate: "Дата народження",
    birthdatePlaceholder: "РР-ММ-РРРР",
    weight: "Вага (кг)",
    color: "Забарвлення",
    colorPlaceholder: "Колір забарвлення",
    gender: "Стать",
    male: "Хлопчик",
    female: "Дівчинка",
    save: "Зберегти тварину",
    saving: "Збереження...",
    cancel: "Скасувати",
    back: "Назад",
    delete: "Видалити",
    errorName: "Вкажіть ім'я тварини",
    errorBirthdate: "Вкажіть дату народження",
    errorBirthdateFormat: "Невірний формат дати. Використовуйте ДД-ММ-РРРР",
    photoTitle: "Фото тварини",
    photoCamera: "Камера",
    photoGallery: "Галерея",
    cameraDenied: "Потрібен дозвіл на використання камери",
    permissionTitle: "Дозвіл",
    age: "Вік",
    lessThanMonth: "< 1 міс.",
    months: (n: number) => `${n} міс.`,
    oneYear: "1 рік",
    years2to4: (n: number) => `${n} роки`,
    yearsMany: (n: number) => `${n} років`,
    vaccinations: "Вакцинації",
    addVaccination: "Додати вакцинацію",
    noVaccinations: "Немає вакцинацій",
    documents: "Документи",
    addDocument: "Додати документ",
    noDocuments: "Немає документів",
    overdue: "Прострочено",
    soon7days: "Незабаром (7 днів)",
    thisMonth: "Цього місяця",
    planned: "Заплановано",
    next: "Наступна",
    done: "Зроблено",
    vet: "Ветеринар",
    notes: "Нотатки",
    profile: "Профіль тварини",
    details: "Деталі",
    seeAll: "Всі",
    newVaccine: "Нова вакцина",
    vaccineReminder: "Ви отримаєте нагадування за 7 днів до наступної вакцинації",
    quickPick: "Швидкий вибір",
    vaccinationInfo: "Інформація про вакцинацію",
    vaccineName: "Назва вакцини",
    vaccineDate: "Дата вакцинації",
    nextVaccineDate: "Наступна вакцинація",
    additionalInfo: "Додаткова інформація",
    saveVaccination: "Зберегти вакцинацію",
    deleteVaccination: "Видалити вакцинацію?",
    deleteVaccinationConfirm: "Вакцинацію буде видалено безповоротно.",
    deleteDoc: "Видалити документ?",
    deleteDocConfirm: "Документ буде видалено зі списку.",
    deletePet: "Видалити",
    deletePetConfirm: "Всі дані тварини будуть видалені безповоротно.",
    docTakePhoto: "Зробити фото",
    docGallery: "Вибрати з галереї",
    docFiles: "Вибрати з файлів",
    docCount: (n: number) => `${n} документів збережено`,
    language: "Мова",
    ukrainian: "Українська",
    english: "English",
    appearance: "Вигляд",
    about: "Про додаток",
    version: "Версія",
    notFound: "Тварину не знайдено",
    cat: "Кіт",
    dog: "Собака",
    rabbit: "Кролик",
    hamster: "Хом'як",
    guinea_pig: "Морська свинка",
    bird: "Птах",
    turtle: "Черепаха",
    reptile: "Рептилія",
    fish: "Риба",
    ferret: "Тхір",
    hedgehog: "Їжак",
    other: "Інше",
    selectBreed: "Оберіть породу",
    customBreed: "Інша порода",
    weightSelect: "Вага",
    today: "Сьогодні",
    error: "Помилка",
    errorEmail: "Введіть ваш email",
    errorVaccineName: "Вкажіть назву вакцини",
    errorVaccineDate: "Вкажіть дату вакцинації",
    errorVaccineNextDate: "Вкажіть дату наступної вакцинації",
    vetNamePlaceholder: "Ім'я ветеринара",
    notesPlaceholder: "Додаткові нотатки...",
    forgotPasswordTitle: "Відновлення паролю",
    forgotPasswordHeading: "Забули пароль?",
    forgotPasswordSubtitle: "Введіть email пов'язаний з вашим акаунтом — ми надішлемо посилання для відновлення.",
    forgotPasswordBtn: "Надіслати посилання",
    forgotPasswordSending: "Надсилаємо...",
    forgotPasswordSuccess: "Лист надіслано!",
    forgotPasswordSuccessText: (email: string) => `Перевірте вашу пошту ${email} і перейдіть за посиланням для відновлення паролю.`,
    forgotPasswordBack: "Повернутись до входу",
    loginError: "Помилка входу",
    providerNotEnabled: (name: string) => `${name} вхід ще не налаштовано. Зверніться до адміністратора.`,
    networkError: "Помилка мережі. Перевірте підключення.",
    signInWithApple: "Увійти через Apple",
    newReminder: "Нове нагадування",
    petLabel: "Тварина",
    reminderTypeLabel: "Тип нагадування",
    nextDateLabel: "Наступна дата",
    addReminderBtn: "Додати нагадування",
    addReminderAdd: "Додати",
    enterDate: "Вкажіть дату",
    daysAgo: (n: number) => `${n} дн. тому`,
    inDays: (n: number) => `через ${n} дн.`,
    weightLog: "Журнал ваги",
    sessionExpired: "Сесія закінчилась. Будь ласка, увійдіть знову.",
    eventsTabLabel: "Події",
    nearest: "Найближча",
    // Health events
    healthEvents: "Здоров'я та події",
    addHealthEvent: "Додати подію",
    noHealthEvents: "Немає подій",
    noHealthEventsSubtitle: "Натисніть + щоб додати першу подію",
    upcomingEvents: "Найближчі події",
    pastEvents: "Минулі події",
    allEvents: "Всі",
    eventType: "Тип події",
    eventTitle: "Назва",
    eventTitlePlaceholder: "Назва події або препарату",
    eventDate: "Дата",
    eventTime: "Час (необов'язково)",
    eventNextDate: "Наступна дата",
    eventNextTime: "Наступний час (необов'язково)",
    contactName: "Контакт (ім'я)",
    contactNamePlaceholder: "Ім'я спеціаліста",
    contactPhone: "Телефон",
    contactPhonePlaceholder: "+380...",
    contactAddress: "Адреса",
    contactAddressPlaceholder: "Адреса закладу",
    saveHealthEvent: "Зберегти подію",
    savingHealthEvent: "Збереження...",
    deleteHealthEvent: "Видалити подію?",
    deleteHealthEventConfirm: "Подію буде видалено безповоротно.",
    markDone: "Виконано",
    markDoneAndSchedule: "Виконано + наступна",
    eventStatusActive: "Активна",
    eventStatusDone: "Виконана",
    eventStatusCancelled: "Скасована",
    tomorrow: "Завтра",
    daysLeft: (n: number) => `${n} дн.`,
    callBtn: "Зателефонувати",
    smsBtn: "SMS",
    viberBtn: "Viber",
    telegramBtn: "Telegram",
    whatsappBtn: "WhatsApp",
    errorEventTitle: "Вкажіть назву події",
    errorEventDate: "Вкажіть дату події",
    // Recurrence
    recurrenceLabel: "Повторення",
    recurrenceOneTime: "Одноразова",
    recurrenceRepeating: "Повторювана",
    recurrenceRegular: "Регулярна",
    repeatIntervalLabel: "Повторювати кожні",
    repeatUnitDays: "дн.",
    repeatUnitWeeks: "тиж.",
    repeatUnitMonths: "міс.",
    // Status labels
    statusPlanned: "Заплановано",
    statusActive: "Активно",
    statusOverdue: "Прострочено",
    statusDone: "Виконано",
    // Schedule next prompt
    scheduleNextTitle: "Запланувати наступну?",
    scheduleNextConfirm: "Запланувати",
    scheduleNextNo: "Ні",
    scheduleNextYes: "Так",
    repeatUnitYears: "р.",
    // Health event type labels
    he_vaccination:   "Вакцинація",
    he_deworming:     "Глистогінне",
    he_flea_tick:     "Від бліх та кліщів",
    he_checkup:       "Огляд у ветеринара",
    he_grooming:      "Грумінг",
    he_psychologist:  "Зоопсихолог",
    he_training:      "Тренування",
    he_competition:   "Змагання",
    he_exhibition:    "Виставка",
    he_nail_trim:     "Стрижка кігтів",
    he_analysis:      "Аналізи",
    he_rabies:        "Від сказу",
    he_chipping:      "Чіпування",
    he_insurance:     "Страховка",
    he_birthday:      "День народження",
    he_other:         "Інше",
    // New event type labels
    he_vet:           "Ветеринар",
    he_surgery:       "Операція",
    he_medication:    "Прийом ліків",
    he_sterilization: "Стерилізація/кастрація",
    he_bath:          "Купання",
    he_ear_cleaning:  "Чистка вух",
    he_teeth_cleaning:"Чистка зубів",
    he_dog_trainer:   "Кінолог",
    he_walk:          "Вигул",
    he_boarding:      "Перетримка",
    he_family_day:    "День появи в сім'ї",
    he_mating:        "В'язка",
    he_certification: "Сертифікація",
    he_registration:  "Реєстрація",
    he_custom:        "Власна подія",
    // Template selection screen
    selectEventTitle:     "Оберіть подію",
    createCustomEvent:    "Створити власну подію",
    searchEventPlaceholder: "Пошук події...",
    sortLabel:            "Сортування",
    sortSmart:            "Розумне",
    sortFrequent:         "Найчастіші вгорі",
    sortRecent:           "Нещодавні вгорі",
    sortCustomFirst:      "Користувацькі вгорі",
    sortAlpha:            "За алфавітом",
    deleteTemplate:       "Видалити шаблон?",
    deleteTemplateConfirm:(name: string) => `«${name}» буде видалено безповоротно.`,
    // Custom template creation screen
    createTemplateTitle:  "Новий шаблон",
    templateNameLabel:    "Назва шаблону",
    templateNamePlaceholder: "Введіть назву...",
    templateIconLabel:    "Оберіть іконку",
    saveTemplate:         "Зберегти шаблон",
    errorTemplateName:    "Вкажіть назву шаблону",
    errorTemplateIcon:    "Оберіть іконку",
  },
  en: {
    appName: "Tailsy",
    pets: "Pets",
    reminders: "Reminders",
    settings: "Settings",
    addPet: "Add Pet",
    noPets: "No Pets Yet",
    noPetsSubtitle: "Tap + to add your first pet",
    noReminders: "No Reminders",
    noRemindersSubtitle: "Add vaccinations to get reminders",
    remindersTotal: (n: number) => `${n} vaccinations scheduled`,
    onePet: "1 pet",
    manyPets: (n: number) => `${n} pets`,
    addPetTitle: "Add Pet",
    petType: "Pet Type",
    basicInfo: "Basic Information",
    name: "Name",
    namePlaceholder: "Your pet's name",
    breed: "Breed",
    breedPlaceholder: "Select or enter breed",
    birthdate: "Date of Birth",
    birthdatePlaceholder: "DD-MM-YYYY",
    weight: "Weight (kg)",
    color: "Coat Color",
    colorPlaceholder: "Color / markings",
    gender: "Gender",
    male: "Male",
    female: "Female",
    save: "Save Pet",
    saving: "Saving...",
    cancel: "Cancel",
    back: "Back",
    delete: "Delete",
    errorName: "Please enter pet name",
    errorBirthdate: "Please enter date of birth",
    errorBirthdateFormat: "Invalid date format. Use DD-MM-YYYY",
    photoTitle: "Pet Photo",
    photoCamera: "Camera",
    photoGallery: "Gallery",
    cameraDenied: "Camera permission is required",
    permissionTitle: "Permission",
    age: "Age",
    lessThanMonth: "< 1 mo.",
    months: (n: number) => `${n} mo.`,
    oneYear: "1 year",
    years2to4: (n: number) => `${n} years`,
    yearsMany: (n: number) => `${n} years`,
    vaccinations: "Vaccinations",
    addVaccination: "Add Vaccination",
    noVaccinations: "No Vaccinations",
    documents: "Documents",
    addDocument: "Add Document",
    noDocuments: "No Documents",
    overdue: "Overdue",
    soon7days: "Due Soon (7 days)",
    thisMonth: "This Month",
    planned: "Planned",
    next: "Next",
    done: "Done",
    vet: "Veterinarian",
    notes: "Notes",
    profile: "Pet Profile",
    details: "Details",
    seeAll: "All",
    newVaccine: "New Vaccine",
    vaccineReminder: "You will get a reminder 7 days before the next vaccination",
    quickPick: "Quick Pick",
    vaccinationInfo: "Vaccination Info",
    vaccineName: "Vaccine Name",
    vaccineDate: "Vaccination Date",
    nextVaccineDate: "Next Vaccination",
    additionalInfo: "Additional Info",
    saveVaccination: "Save Vaccination",
    deleteVaccination: "Delete Vaccination?",
    deleteVaccinationConfirm: "This vaccination will be permanently deleted.",
    deleteDoc: "Delete Document?",
    deleteDocConfirm: "This document will be removed from the list.",
    deletePet: "Delete",
    deletePetConfirm: "All pet data will be permanently deleted.",
    docTakePhoto: "Take Photo",
    docGallery: "Choose from Gallery",
    docFiles: "Browse Files",
    docCount: (n: number) => `${n} documents stored`,
    language: "Language",
    ukrainian: "Українська",
    english: "English",
    appearance: "Appearance",
    about: "About",
    version: "Version",
    notFound: "Pet not found",
    cat: "Cat",
    dog: "Dog",
    rabbit: "Rabbit",
    hamster: "Hamster",
    guinea_pig: "Guinea Pig",
    bird: "Bird",
    turtle: "Turtle",
    reptile: "Reptile",
    fish: "Fish",
    ferret: "Ferret",
    hedgehog: "Hedgehog",
    other: "Other",
    selectBreed: "Select Breed",
    customBreed: "Other breed",
    weightSelect: "Weight",
    today: "Today",
    error: "Error",
    errorEmail: "Please enter your email",
    errorVaccineName: "Enter vaccine name",
    errorVaccineDate: "Enter vaccination date",
    errorVaccineNextDate: "Enter next vaccination date",
    vetNamePlaceholder: "Veterinarian name",
    notesPlaceholder: "Additional notes...",
    forgotPasswordTitle: "Reset Password",
    forgotPasswordHeading: "Forgot password?",
    forgotPasswordSubtitle: "Enter the email linked to your account — we'll send a recovery link.",
    forgotPasswordBtn: "Send Link",
    forgotPasswordSending: "Sending...",
    forgotPasswordSuccess: "Email Sent!",
    forgotPasswordSuccessText: (email: string) => `Check your inbox at ${email} and follow the link to reset your password.`,
    forgotPasswordBack: "Back to Login",
    loginError: "Sign In Error",
    providerNotEnabled: (name: string) => `${name} sign in is not configured. Contact the administrator.`,
    networkError: "Network error. Check your connection.",
    signInWithApple: "Sign in with Apple",
    newReminder: "New Reminder",
    petLabel: "Pet",
    reminderTypeLabel: "Reminder Type",
    nextDateLabel: "Next Date",
    addReminderBtn: "Add Reminder",
    addReminderAdd: "Add",
    enterDate: "Please enter a date",
    daysAgo: (n: number) => `${n} days ago`,
    inDays: (n: number) => `in ${n} days`,
    weightLog: "Weight Log",
    sessionExpired: "Session expired. Please sign in again.",
    eventsTabLabel: "Events",
    nearest: "Nearest",
    // Health events
    healthEvents: "Health & Events",
    addHealthEvent: "Add Event",
    noHealthEvents: "No Events",
    noHealthEventsSubtitle: "Tap + to add the first event",
    upcomingEvents: "Upcoming Events",
    pastEvents: "Past Events",
    allEvents: "All",
    eventType: "Event Type",
    eventTitle: "Title",
    eventTitlePlaceholder: "Event name or product",
    eventDate: "Date",
    eventTime: "Time (optional)",
    eventNextDate: "Next Date",
    eventNextTime: "Next Time (optional)",
    contactName: "Contact (name)",
    contactNamePlaceholder: "Specialist name",
    contactPhone: "Phone",
    contactPhonePlaceholder: "+1...",
    contactAddress: "Address",
    contactAddressPlaceholder: "Clinic address",
    saveHealthEvent: "Save Event",
    savingHealthEvent: "Saving...",
    deleteHealthEvent: "Delete Event?",
    deleteHealthEventConfirm: "This event will be permanently deleted.",
    markDone: "Done",
    markDoneAndSchedule: "Done + Next",
    eventStatusActive: "Active",
    eventStatusDone: "Done",
    eventStatusCancelled: "Cancelled",
    tomorrow: "Tomorrow",
    daysLeft: (n: number) => `${n}d`,
    callBtn: "Call",
    smsBtn: "SMS",
    viberBtn: "Viber",
    telegramBtn: "Telegram",
    whatsappBtn: "WhatsApp",
    errorEventTitle: "Please enter event title",
    errorEventDate: "Please enter event date",
    // Recurrence
    recurrenceLabel: "Recurrence",
    recurrenceOneTime: "One-time",
    recurrenceRepeating: "Repeating",
    recurrenceRegular: "Regular",
    repeatIntervalLabel: "Repeat every",
    repeatUnitDays: "d",
    repeatUnitWeeks: "wk",
    repeatUnitMonths: "mo",
    // Status labels
    statusPlanned: "Planned",
    statusActive: "Active",
    statusOverdue: "Overdue",
    statusDone: "Done",
    // Schedule next prompt
    scheduleNextTitle: "Schedule next?",
    scheduleNextConfirm: "Schedule",
    scheduleNextNo: "No",
    scheduleNextYes: "Yes",
    repeatUnitYears: "yr",
    // Health event type labels
    he_vaccination: "Vaccination",
    he_deworming: "Deworming",
    he_flea_tick: "Flea & Tick",
    he_checkup: "Vet Checkup",
    he_grooming: "Grooming",
    he_psychologist: "Behaviorist",
    he_training: "Training",
    he_competition: "Competition",
    he_exhibition: "Exhibition",
    he_nail_trim:      "Nail Trim",
    he_analysis:       "Analysis",
    he_rabies:         "Rabies",
    he_chipping:       "Microchipping",
    he_insurance:      "Insurance",
    he_birthday:       "Birthday",
    he_other:          "Other",
    // New event type labels
    he_vet:            "Vet Visit",
    he_surgery:        "Surgery",
    he_medication:     "Medication",
    he_sterilization:  "Sterilization",
    he_bath:           "Bath",
    he_ear_cleaning:   "Ear Cleaning",
    he_teeth_cleaning: "Teeth Cleaning",
    he_dog_trainer:    "Dog Trainer",
    he_walk:           "Walk",
    he_boarding:       "Boarding",
    he_family_day:     "Adoption Day",
    he_mating:         "Mating",
    he_certification:  "Certification",
    he_registration:   "Registration",
    he_custom:         "Custom Event",
    // Template selection screen
    selectEventTitle:       "Choose an Event",
    createCustomEvent:      "Create Custom Event",
    searchEventPlaceholder: "Search events...",
    sortLabel:              "Sort",
    sortSmart:              "Smart",
    sortFrequent:           "Most Used First",
    sortRecent:             "Recent First",
    sortCustomFirst:        "Custom First",
    sortAlpha:              "Alphabetical",
    deleteTemplate:         "Delete Template?",
    deleteTemplateConfirm:  (name: string) => `«${name}» will be permanently deleted.`,
    // Custom template creation screen
    createTemplateTitle:     "New Template",
    templateNameLabel:       "Template Name",
    templateNamePlaceholder: "Enter name...",
    templateIconLabel:       "Choose an Icon",
    saveTemplate:            "Save Template",
    errorTemplateName:       "Please enter a template name",
    errorTemplateIcon:       "Please choose an icon",
  },
} as const;

export type Translations = typeof translations.uk;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const STORAGE_KEY = "@vethelper_language";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("uk");

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY).then((val) => {
      if (val === "uk" || val === "en") setLanguageState(val);
    });
  }, []);

  const setLanguage = useCallback(async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem(STORAGE_KEY, lang);
  }, []);

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t: translations[language] }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
