export const CAT_BREEDS_UK = [
  "Британська короткошерста",
  "Шотландська висловуха",
  "Мейн-кун",
  "Сибірська",
  "Перська",
  "Бенгальська",
  "Рагдол",
  "Норвезька лісова",
  "Абіссінська",
  "Бурманська",
  "Сфінкс",
  "Орієнтальна",
  "Сомалійська",
  "Турецька ангора",
  "Ексзотична короткошерста",
  "Балійська",
  "Бірманська",
  "Девон-рекс",
  "Корніш-рекс",
  "Тонкінська",
  "Єгипетська мау",
  "Руська блакитна",
  "Невська маскарадна",
  "Шартрез",
  "Бурмілла",
  "Пікся-боб",
  "Американська короткошерста",
  "Сіамська",
  "Оцикет",
  "Змішана порода",
];

export const DOG_BREEDS_UK = [
  "Лабрадор ретрівер",
  "Німецька вівчарка",
  "Золотистий ретрівер",
  "Французький бульдог",
  "Йоркширський тер'єр",
  "Чихуахуа",
  "Хаскі",
  "Мопс",
  "Такса",
  "Бігль",
  "Шпіц",
  "Пудель",
  "Доберман",
  "Боксер",
  "Ротвейлер",
  "Бордер-коллі",
  "Австралійська вівчарка",
  "Коккер-спанієль",
  "Джек-рассел-тер'єр",
  "Шнауцер",
  "Маламут",
  "Самоїд",
  "Далматинець",
  "Бульмастиф",
  "Акіта",
  "Шарпей",
  "Кавалер-кінг-чарльз-спанієль",
  "Ірландський сетер",
  "Веймаранер",
  "Змішана порода",
];

export const CAT_BREEDS_EN = [
  "British Shorthair",
  "Scottish Fold",
  "Maine Coon",
  "Siberian",
  "Persian",
  "Bengal",
  "Ragdoll",
  "Norwegian Forest Cat",
  "Abyssinian",
  "Burmese",
  "Sphynx",
  "Oriental",
  "Somali",
  "Turkish Angora",
  "Exotic Shorthair",
  "Balinese",
  "Birman",
  "Devon Rex",
  "Cornish Rex",
  "Tonkinese",
  "Egyptian Mau",
  "Russian Blue",
  "Neva Masquerade",
  "Chartreux",
  "Burmilla",
  "Pixie-Bob",
  "American Shorthair",
  "Siamese",
  "Ocicat",
  "Mixed Breed",
];

export const DOG_BREEDS_EN = [
  "Labrador Retriever",
  "German Shepherd",
  "Golden Retriever",
  "French Bulldog",
  "Yorkshire Terrier",
  "Chihuahua",
  "Husky",
  "Pug",
  "Dachshund",
  "Beagle",
  "Spitz",
  "Poodle",
  "Doberman",
  "Boxer",
  "Rottweiler",
  "Border Collie",
  "Australian Shepherd",
  "Cocker Spaniel",
  "Jack Russell Terrier",
  "Schnauzer",
  "Malamute",
  "Samoyed",
  "Dalmatian",
  "Bullmastiff",
  "Akita",
  "Shar Pei",
  "Cavalier King Charles Spaniel",
  "Irish Setter",
  "Weimaraner",
  "Mixed Breed",
];
